export const SUBJECTS = [
  'Mathematics',
  'Physical Sciences',
  'Life Sciences',
  'Geography',
  'History',
  'Accounting',
  'Business Studies',
  'Economics',
  'English Home Language',
  'English First Additional',
  'Afrikaans',
  'Xitsonga Home Langauge',
  'Life Orientation',
  'Mathematical Literacy',
  'Agricultural Sciences',
  'Computer Applications Technology',
  'Information Technology',
];

export const SUBJECT_COLORS = {
  Mathematics: '#6C5CE7',
  'Physical Sciences': '#00B894',
  'Life Sciences': '#FD79A8',
  Geography: '#FDCB6E',
  History: '#FF7675',
  Accounting: '#74B9FF',
  'Business Studies': '#A29BFE',
  Economics: '#00CEC9',
  'English Home Language': '#FFAA00',
  'English First Additional': '#E17055',
  Afrikaans: '#0984E3',
  'Xitsonga Home Langauge' : '#D63031',
  'Life Orientation': '#FAB1A0',
  'Mathematical Literacy': '#55EFC4',
  'Agricultural Sciences': '#00B894',
  'Computer Applications Technology': '#6C5CE7',
  'Information Technology': '#6C5CE7',
};